apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsegmentation-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: microsegmentation-operator
  template:
    metadata:
      labels:
        name: microsegmentation-operator
    spec:
      serviceAccountName: microsegmentation-operator
      containers:
        - name: microsegmentation-operator
          # Replace this with the built image name
          image: quay.io/eformat/microsegmentation-operator:latest
          command:
          - microsegmentation-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "microsegmentation-operator"
