kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: microsegmentation-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*" 
- apiGroups:
  - "networking"
  resources:
  - networkpolicies
  verbs:
  - "*"   
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: microsegmentation-operator
rules:
# leader election   
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "*"  
#Metrics  
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
#Metrics  
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs: 
  - "get"
  - "list"
# Metrics  
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
# Metrics  
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - cert-utils-operator
  verbs:
  - "update"

